// <auto-generated />
using ApiBancoDigital.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiBancoDigital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210729195246_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ApiBancoDigital.Models.ContaDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Conta")
                        .HasColumnType("int");

                    b.Property<double>("Saldo")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("ContasDigitais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Conta = 1,
                            Saldo = 999.0
                        },
                        new
                        {
                            Id = 2,
                            Conta = 2,
                            Saldo = 999.0
                        },
                        new
                        {
                            Id = 3,
                            Conta = 3,
                            Saldo = 999.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
